### ISSUE TITLE
Weird Linking Errors with 10/01 Prebuilts on Marshmallow

### ISSUE THREAD

**Issue by airend** [UBERTC/binutils#1] opened 2015-10-22 19:59 UTC
Using the same 10/01 Android EABI (4.9) as on LP, I'm suddenly getting fatal ld errors:

`[…]ld: warning: hidden symbol '__aeabi_unwind_cpp_pr1' in […]out/target/product/ovation/obj/STATIC_LIBRARIES/libunwind_llvm_intermediates/libunwind_llvm.a(Unwind-EHABI.o) is referenced by DSO […]out/target/product/ovation/system/vendor/lib/libsrv_um_SGX544_112.so`

followed by `ld: error: treating warnings as errors` and build failure. Thanks for any help with this.

**Comment by Cl3Kener** [comment] 2015-10-22 20:43
Did you wipe cache? Most weird linker type errors are not errors caused by toolchain but by ccache and users failing to wipe it when changing projects....

**Comment by airend** [comment] 2015-10-22 21:13
Yup, several times, before I remembered to test the AOSP prebuilts. If no other report of this kind, maybe I'm doing something else wrong here, especially given these old SGX blobs.

**Comment by Cl3Kener** [comment] 2015-10-22 22:31
@airend I'll need a the last 300 lines or so of the log then. Use http://hastebin.com/ to post I don't get enough info out of these 2 lines only.

**Comment by airend** [comment] 2015-10-23 05:29
I made the problem package ([pvrsrvinit](https://github.com/OMAP4-AOSP/android_hardware_ti_omap4/tree/aosp-6.0/pvrsrvinit)) with `-j1 V=s`, just in case. Here's the full output after `ccache -C`: http://hastebin.com/ujusujefac.pl (except all the irrelevant AOSP build system includes). Things are OK when I go back to the AOSP prebuilts. P.S. Just tested Linaro 4.9-2015.06, and it fails similarly (http://hastebin.com/unowuwimir.hs).

**Comment by Cl3Kener** [comment] 2015-10-23 17:39
@airend I'm going to see if there is a way to merge in some aosp changes to binutils and maybe that will fix the issue.  Linaro and I use binutils simlar to the gnu.org trunk which is why we both have the same issue which must have been resolved by aosp

**Comment by airend** [comment] 2015-10-25 23:56
Thanks a lot for looking into this, @Cl3Kener. Of all the toolchains I tested, yours worked best on my devices (Krait & OMAP4). Also, possible good news: that problem module fully compiles/links with the 10/25 prebuilts. I'll update in a few hours, once the full AOSP ROM is done, hopefully ;-)

_Update_: It finished indeed. Whatever you merged lately fixed the linking issues. Thanks again.

**Closed as completed** 2015-10-26 02:31 UTC
